### ISSUE TITLE
Handling of inequality requirements operators

### ISSUE THREAD

**Issue by radekhromadka** [MousaZeidBaker/poetryup#41] opened 2022-05-04 16:42 UTC
Adding handling for [inequality requirements](https://python-poetry.org/docs/dependency-specification/#inequality-requirements) in dependencies. Don't have right to create new branches but before I figured that out what I came up with was rewriting the constraint as:
>     @property
>     def constraint(self) -> str:
>         if type(self.version) is items.String:
>             if self.version[:2].startswith(("^", "~", ">", "<")):
>                 if self.version[:2].startswith((">=", "<=")):
>                     return self.version[:2]
>                 else:
>                     return self.version[0]
>         elif type(self.version) is items.InlineTable:
>             if self.version.get("version", "").startswith(("^", "~", ">", "<")):
>                 if self.version.get("version", "").startswith((">=", "<=")):
>                     return self.version["version"][:2]
>                 else:
>                     return self.version["version"][0]
>         return ""  # dependencies with exact version or multiple versions
Though there are probably cleaner ways of doing this. Didn't add != as I do not think that this should be persistent after a version bump. Though x2 that just made me realize that I am not clear on how poetryup itself handles <=, I assume it just ignores it? Might be pointless to add or require additional handling

**Comment by MousaZeidBaker** [comment] 2022-05-06 18:29
Thanks for reporting an issue @radekhromadka 

I think it could be solved cleaner if we take advantage of the `Dependency` class somehow, though it will require some refactoring of the `constraint`. I'm working on it. 

Right now `poetryup` removes any non `caret` & `tilde` constraints due to [this line](https://github.com/MousaZeidBaker/poetryup/blob/master/src/poetryup/pyproject.py#L33). So a dependency with version `!=x.y.1` becomes `x.y.2` after running poetryup and that is not desired outcome.

**Comment by MousaZeidBaker** [comment] 2022-05-07 20:35
Hey again @radekhromadka 

I think we can only handle/bump specifications with `>=`. See following examples:
    - assume a dep with `>=0.1.0` and we update to `0.5.0` -> safe to bump to `>=0.5.0`
    - assume a dep with `>0.1.0` and we update to `0.5.0` -> NOT safe to bump because we don't know the previous version
    - assume a dep with `<=0.2.0` and we update to `0.6.0` -> doesn't make sense to bump since spec says less than or equal
    - assume a dep with `<0.2.0` and we update to `0.6.0` -> doesn't make sense to bump since spec says less than
    - assume a dep with `!=0.1.0` and we update to `0.7.0` -> doesn't make sense to bump since spec says not equal to

**Comment by dimbleby** [comment] 2022-05-09 08:45
`>=` seems much more likely to be encountered in the wild, but I'm not sure why it wouldn't be safe to bump `>`?

**Comment by MousaZeidBaker** [comment] 2022-05-09 09:22
Because the version prior to the updated one is not known by `poetryup`. Following is an extended example:

Consider a dependency specified with `>0.1.0` in `pyproject.toml` and let say currently installed version is `0.2.0`. At the time of updating the dependency there are multiple new versions available: `0.3.0`, `0.4.0`, `0.5.0`, we end up with `0.5.0` (latest) version since the specifications says "greater than". 

Now what should the version in `pyproject.toml` be bumped to? Ideally to `>0.4.0` since this version is prior to the one we just updated to. the issue is that  `poetryup` doesn't know about this version. And you can't bump to `>0.5.0` because that would be in conflict with what we just currently updated to. So that leaves us with the only option to just leave it as it is, unless you know something else?

**Comment by dimbleby** [comment] 2022-05-09 09:24
Ah, I see, the danger is that we leave ourselves with an unsatisfiable constraint if we just preserve the `>`.

I guess `>0.1.0` could safely be converted to `>=0.5.0`, but perhaps this is more trouble than it's worth.

**Comment by MousaZeidBaker** [comment] 2022-05-09 09:33
> I guess >0.1.0 could safely be converted to >=0.5.0, but perhaps this is more trouble than it's worth.

Hmm yes we could actually do that.. but I'm not sure its the responsibility of `poetryup` to do that. I'd rather let the end user have control over the constraints instead of letting `poetryup` change them. What do you think? We could though document that the recommended constrains are `caret`, `tilde` and `>=`.

**Comment by dimbleby** [comment] 2022-05-09 09:34
I don't mind either way, I've never used nor intend to use a `>` constraint.  `>=` all the time though!

**Comment by MousaZeidBaker** [comment] 2022-05-09 09:41
Then lets keep it like that!

Do you mind testing the changes I made? You can install from the branch with the following:
`poetry add git+https://github.com/MousaZeidBaker/poetryup.git#feat/version-constraints`

If it works as intended, I can go ahead and merge the changes.

**Comment by dimbleby** [comment] 2022-05-09 10:31
Works for me.

There's slightly surprising output in `poetryup --latest` where the update reports that it is `using version ^1.2.3 for foo` (and, I think, actually does put that version into `pyproject.toml`).  But then it rewrites that file so that it actually contains `foo = ">=1.2.3"`.

But that's cosmetic at most, the final outcome seems to be as expected.

**Comment by MousaZeidBaker** [comment] 2022-05-09 11:05
Hmm when you run `poetryup --latest` PoetryUp runs `poetry add foo@latest` in the background so when you see `Using version ^1.2.3 for foo` thats the output from Poetry itself (not PoetryUp). Poetry also also applies its own changes to `pyproject.toml` and only when its done, PoetryUp kicks in and reverts the constraint back to what they used to be. The issue is that we need to run [poetry lock](https://python-poetry.org/docs/cli/#lock) after modifying `pyproject.toml` in order to keep `poetry.lock` file up to date.

**Comment by dimbleby** [comment] 2022-05-09 11:07
yeah, `poetry lock --no-update` maybe so as to avoid re-resolving everything

**Comment by MousaZeidBaker** [comment] 2022-05-09 11:30
Created [separate PR 44](https://github.com/MousaZeidBaker/poetryup/pull/44) for refreshing lock file as that is a bug thats always been there and is unrelated to this issue. Will merge PR 44 first and then PR for this issue. 

And great catch btw, haven't noticed it before.

**Closed** 2022-05-09 11:36 UTC
